// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nettyDemo.proto

package com.hoang.plugins;

public final class NettyDemo {
  private NettyDemo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface IndexDataStreamOrBuilder extends
      // @@protoc_insertion_point(interface_extends:IndexDataStream)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .DataStream dataStream = 1;</code>
     */
    java.util.List<com.hoang.plugins.NettyDemo.DataStream> 
        getDataStreamList();
    /**
     * <code>repeated .DataStream dataStream = 1;</code>
     */
    com.hoang.plugins.NettyDemo.DataStream getDataStream(int index);
    /**
     * <code>repeated .DataStream dataStream = 1;</code>
     */
    int getDataStreamCount();
    /**
     * <code>repeated .DataStream dataStream = 1;</code>
     */
    java.util.List<? extends com.hoang.plugins.NettyDemo.DataStreamOrBuilder> 
        getDataStreamOrBuilderList();
    /**
     * <code>repeated .DataStream dataStream = 1;</code>
     */
    com.hoang.plugins.NettyDemo.DataStreamOrBuilder getDataStreamOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code IndexDataStream}
   */
  public static final class IndexDataStream extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:IndexDataStream)
      IndexDataStreamOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use IndexDataStream.newBuilder() to construct.
    private IndexDataStream(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private IndexDataStream() {
      dataStream_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new IndexDataStream();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private IndexDataStream(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                dataStream_ = new java.util.ArrayList<com.hoang.plugins.NettyDemo.DataStream>();
                mutable_bitField0_ |= 0x00000001;
              }
              dataStream_.add(
                  input.readMessage(com.hoang.plugins.NettyDemo.DataStream.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          dataStream_ = java.util.Collections.unmodifiableList(dataStream_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hoang.plugins.NettyDemo.internal_static_IndexDataStream_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hoang.plugins.NettyDemo.internal_static_IndexDataStream_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hoang.plugins.NettyDemo.IndexDataStream.class, com.hoang.plugins.NettyDemo.IndexDataStream.Builder.class);
    }

    public static final int DATASTREAM_FIELD_NUMBER = 1;
    private java.util.List<com.hoang.plugins.NettyDemo.DataStream> dataStream_;
    /**
     * <code>repeated .DataStream dataStream = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.hoang.plugins.NettyDemo.DataStream> getDataStreamList() {
      return dataStream_;
    }
    /**
     * <code>repeated .DataStream dataStream = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.hoang.plugins.NettyDemo.DataStreamOrBuilder> 
        getDataStreamOrBuilderList() {
      return dataStream_;
    }
    /**
     * <code>repeated .DataStream dataStream = 1;</code>
     */
    @java.lang.Override
    public int getDataStreamCount() {
      return dataStream_.size();
    }
    /**
     * <code>repeated .DataStream dataStream = 1;</code>
     */
    @java.lang.Override
    public com.hoang.plugins.NettyDemo.DataStream getDataStream(int index) {
      return dataStream_.get(index);
    }
    /**
     * <code>repeated .DataStream dataStream = 1;</code>
     */
    @java.lang.Override
    public com.hoang.plugins.NettyDemo.DataStreamOrBuilder getDataStreamOrBuilder(
        int index) {
      return dataStream_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < dataStream_.size(); i++) {
        output.writeMessage(1, dataStream_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < dataStream_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, dataStream_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.hoang.plugins.NettyDemo.IndexDataStream)) {
        return super.equals(obj);
      }
      com.hoang.plugins.NettyDemo.IndexDataStream other = (com.hoang.plugins.NettyDemo.IndexDataStream) obj;

      if (!getDataStreamList()
          .equals(other.getDataStreamList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getDataStreamCount() > 0) {
        hash = (37 * hash) + DATASTREAM_FIELD_NUMBER;
        hash = (53 * hash) + getDataStreamList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.hoang.plugins.NettyDemo.IndexDataStream parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hoang.plugins.NettyDemo.IndexDataStream parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hoang.plugins.NettyDemo.IndexDataStream parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hoang.plugins.NettyDemo.IndexDataStream parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hoang.plugins.NettyDemo.IndexDataStream parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hoang.plugins.NettyDemo.IndexDataStream parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hoang.plugins.NettyDemo.IndexDataStream parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hoang.plugins.NettyDemo.IndexDataStream parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hoang.plugins.NettyDemo.IndexDataStream parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.hoang.plugins.NettyDemo.IndexDataStream parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hoang.plugins.NettyDemo.IndexDataStream parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hoang.plugins.NettyDemo.IndexDataStream parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.hoang.plugins.NettyDemo.IndexDataStream prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code IndexDataStream}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:IndexDataStream)
        com.hoang.plugins.NettyDemo.IndexDataStreamOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hoang.plugins.NettyDemo.internal_static_IndexDataStream_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hoang.plugins.NettyDemo.internal_static_IndexDataStream_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hoang.plugins.NettyDemo.IndexDataStream.class, com.hoang.plugins.NettyDemo.IndexDataStream.Builder.class);
      }

      // Construct using com.hoang.plugins.NettyDemo.IndexDataStream.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getDataStreamFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (dataStreamBuilder_ == null) {
          dataStream_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          dataStreamBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hoang.plugins.NettyDemo.internal_static_IndexDataStream_descriptor;
      }

      @java.lang.Override
      public com.hoang.plugins.NettyDemo.IndexDataStream getDefaultInstanceForType() {
        return com.hoang.plugins.NettyDemo.IndexDataStream.getDefaultInstance();
      }

      @java.lang.Override
      public com.hoang.plugins.NettyDemo.IndexDataStream build() {
        com.hoang.plugins.NettyDemo.IndexDataStream result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.hoang.plugins.NettyDemo.IndexDataStream buildPartial() {
        com.hoang.plugins.NettyDemo.IndexDataStream result = new com.hoang.plugins.NettyDemo.IndexDataStream(this);
        int from_bitField0_ = bitField0_;
        if (dataStreamBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            dataStream_ = java.util.Collections.unmodifiableList(dataStream_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.dataStream_ = dataStream_;
        } else {
          result.dataStream_ = dataStreamBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hoang.plugins.NettyDemo.IndexDataStream) {
          return mergeFrom((com.hoang.plugins.NettyDemo.IndexDataStream)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hoang.plugins.NettyDemo.IndexDataStream other) {
        if (other == com.hoang.plugins.NettyDemo.IndexDataStream.getDefaultInstance()) return this;
        if (dataStreamBuilder_ == null) {
          if (!other.dataStream_.isEmpty()) {
            if (dataStream_.isEmpty()) {
              dataStream_ = other.dataStream_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureDataStreamIsMutable();
              dataStream_.addAll(other.dataStream_);
            }
            onChanged();
          }
        } else {
          if (!other.dataStream_.isEmpty()) {
            if (dataStreamBuilder_.isEmpty()) {
              dataStreamBuilder_.dispose();
              dataStreamBuilder_ = null;
              dataStream_ = other.dataStream_;
              bitField0_ = (bitField0_ & ~0x00000001);
              dataStreamBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getDataStreamFieldBuilder() : null;
            } else {
              dataStreamBuilder_.addAllMessages(other.dataStream_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hoang.plugins.NettyDemo.IndexDataStream parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hoang.plugins.NettyDemo.IndexDataStream) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.hoang.plugins.NettyDemo.DataStream> dataStream_ =
        java.util.Collections.emptyList();
      private void ensureDataStreamIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          dataStream_ = new java.util.ArrayList<com.hoang.plugins.NettyDemo.DataStream>(dataStream_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.hoang.plugins.NettyDemo.DataStream, com.hoang.plugins.NettyDemo.DataStream.Builder, com.hoang.plugins.NettyDemo.DataStreamOrBuilder> dataStreamBuilder_;

      /**
       * <code>repeated .DataStream dataStream = 1;</code>
       */
      public java.util.List<com.hoang.plugins.NettyDemo.DataStream> getDataStreamList() {
        if (dataStreamBuilder_ == null) {
          return java.util.Collections.unmodifiableList(dataStream_);
        } else {
          return dataStreamBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .DataStream dataStream = 1;</code>
       */
      public int getDataStreamCount() {
        if (dataStreamBuilder_ == null) {
          return dataStream_.size();
        } else {
          return dataStreamBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .DataStream dataStream = 1;</code>
       */
      public com.hoang.plugins.NettyDemo.DataStream getDataStream(int index) {
        if (dataStreamBuilder_ == null) {
          return dataStream_.get(index);
        } else {
          return dataStreamBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .DataStream dataStream = 1;</code>
       */
      public Builder setDataStream(
          int index, com.hoang.plugins.NettyDemo.DataStream value) {
        if (dataStreamBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataStreamIsMutable();
          dataStream_.set(index, value);
          onChanged();
        } else {
          dataStreamBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .DataStream dataStream = 1;</code>
       */
      public Builder setDataStream(
          int index, com.hoang.plugins.NettyDemo.DataStream.Builder builderForValue) {
        if (dataStreamBuilder_ == null) {
          ensureDataStreamIsMutable();
          dataStream_.set(index, builderForValue.build());
          onChanged();
        } else {
          dataStreamBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .DataStream dataStream = 1;</code>
       */
      public Builder addDataStream(com.hoang.plugins.NettyDemo.DataStream value) {
        if (dataStreamBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataStreamIsMutable();
          dataStream_.add(value);
          onChanged();
        } else {
          dataStreamBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .DataStream dataStream = 1;</code>
       */
      public Builder addDataStream(
          int index, com.hoang.plugins.NettyDemo.DataStream value) {
        if (dataStreamBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataStreamIsMutable();
          dataStream_.add(index, value);
          onChanged();
        } else {
          dataStreamBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .DataStream dataStream = 1;</code>
       */
      public Builder addDataStream(
          com.hoang.plugins.NettyDemo.DataStream.Builder builderForValue) {
        if (dataStreamBuilder_ == null) {
          ensureDataStreamIsMutable();
          dataStream_.add(builderForValue.build());
          onChanged();
        } else {
          dataStreamBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .DataStream dataStream = 1;</code>
       */
      public Builder addDataStream(
          int index, com.hoang.plugins.NettyDemo.DataStream.Builder builderForValue) {
        if (dataStreamBuilder_ == null) {
          ensureDataStreamIsMutable();
          dataStream_.add(index, builderForValue.build());
          onChanged();
        } else {
          dataStreamBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .DataStream dataStream = 1;</code>
       */
      public Builder addAllDataStream(
          java.lang.Iterable<? extends com.hoang.plugins.NettyDemo.DataStream> values) {
        if (dataStreamBuilder_ == null) {
          ensureDataStreamIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, dataStream_);
          onChanged();
        } else {
          dataStreamBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .DataStream dataStream = 1;</code>
       */
      public Builder clearDataStream() {
        if (dataStreamBuilder_ == null) {
          dataStream_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          dataStreamBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .DataStream dataStream = 1;</code>
       */
      public Builder removeDataStream(int index) {
        if (dataStreamBuilder_ == null) {
          ensureDataStreamIsMutable();
          dataStream_.remove(index);
          onChanged();
        } else {
          dataStreamBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .DataStream dataStream = 1;</code>
       */
      public com.hoang.plugins.NettyDemo.DataStream.Builder getDataStreamBuilder(
          int index) {
        return getDataStreamFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .DataStream dataStream = 1;</code>
       */
      public com.hoang.plugins.NettyDemo.DataStreamOrBuilder getDataStreamOrBuilder(
          int index) {
        if (dataStreamBuilder_ == null) {
          return dataStream_.get(index);  } else {
          return dataStreamBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .DataStream dataStream = 1;</code>
       */
      public java.util.List<? extends com.hoang.plugins.NettyDemo.DataStreamOrBuilder> 
           getDataStreamOrBuilderList() {
        if (dataStreamBuilder_ != null) {
          return dataStreamBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(dataStream_);
        }
      }
      /**
       * <code>repeated .DataStream dataStream = 1;</code>
       */
      public com.hoang.plugins.NettyDemo.DataStream.Builder addDataStreamBuilder() {
        return getDataStreamFieldBuilder().addBuilder(
            com.hoang.plugins.NettyDemo.DataStream.getDefaultInstance());
      }
      /**
       * <code>repeated .DataStream dataStream = 1;</code>
       */
      public com.hoang.plugins.NettyDemo.DataStream.Builder addDataStreamBuilder(
          int index) {
        return getDataStreamFieldBuilder().addBuilder(
            index, com.hoang.plugins.NettyDemo.DataStream.getDefaultInstance());
      }
      /**
       * <code>repeated .DataStream dataStream = 1;</code>
       */
      public java.util.List<com.hoang.plugins.NettyDemo.DataStream.Builder> 
           getDataStreamBuilderList() {
        return getDataStreamFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.hoang.plugins.NettyDemo.DataStream, com.hoang.plugins.NettyDemo.DataStream.Builder, com.hoang.plugins.NettyDemo.DataStreamOrBuilder> 
          getDataStreamFieldBuilder() {
        if (dataStreamBuilder_ == null) {
          dataStreamBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.hoang.plugins.NettyDemo.DataStream, com.hoang.plugins.NettyDemo.DataStream.Builder, com.hoang.plugins.NettyDemo.DataStreamOrBuilder>(
                  dataStream_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          dataStream_ = null;
        }
        return dataStreamBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:IndexDataStream)
    }

    // @@protoc_insertion_point(class_scope:IndexDataStream)
    private static final com.hoang.plugins.NettyDemo.IndexDataStream DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.hoang.plugins.NettyDemo.IndexDataStream();
    }

    public static com.hoang.plugins.NettyDemo.IndexDataStream getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<IndexDataStream>
        PARSER = new com.google.protobuf.AbstractParser<IndexDataStream>() {
      @java.lang.Override
      public IndexDataStream parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new IndexDataStream(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<IndexDataStream> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<IndexDataStream> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.hoang.plugins.NettyDemo.IndexDataStream getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DataStreamOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DataStream)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string data = 2;</code>
     * @return The data.
     */
    java.lang.String getData();
    /**
     * <code>string data = 2;</code>
     * @return The bytes for data.
     */
    com.google.protobuf.ByteString
        getDataBytes();
  }
  /**
   * Protobuf type {@code DataStream}
   */
  public static final class DataStream extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DataStream)
      DataStreamOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DataStream.newBuilder() to construct.
    private DataStream(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DataStream() {
      name_ = "";
      data_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DataStream();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DataStream(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              data_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hoang.plugins.NettyDemo.internal_static_DataStream_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hoang.plugins.NettyDemo.internal_static_DataStream_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hoang.plugins.NettyDemo.DataStream.class, com.hoang.plugins.NettyDemo.DataStream.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_FIELD_NUMBER = 2;
    private volatile java.lang.Object data_;
    /**
     * <code>string data = 2;</code>
     * @return The data.
     */
    @java.lang.Override
    public java.lang.String getData() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        data_ = s;
        return s;
      }
    }
    /**
     * <code>string data = 2;</code>
     * @return The bytes for data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDataBytes() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (!getDataBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, data_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (!getDataBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.hoang.plugins.NettyDemo.DataStream)) {
        return super.equals(obj);
      }
      com.hoang.plugins.NettyDemo.DataStream other = (com.hoang.plugins.NettyDemo.DataStream) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (!getData()
          .equals(other.getData())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.hoang.plugins.NettyDemo.DataStream parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hoang.plugins.NettyDemo.DataStream parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hoang.plugins.NettyDemo.DataStream parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hoang.plugins.NettyDemo.DataStream parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hoang.plugins.NettyDemo.DataStream parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hoang.plugins.NettyDemo.DataStream parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hoang.plugins.NettyDemo.DataStream parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hoang.plugins.NettyDemo.DataStream parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hoang.plugins.NettyDemo.DataStream parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.hoang.plugins.NettyDemo.DataStream parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hoang.plugins.NettyDemo.DataStream parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hoang.plugins.NettyDemo.DataStream parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.hoang.plugins.NettyDemo.DataStream prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DataStream}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DataStream)
        com.hoang.plugins.NettyDemo.DataStreamOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hoang.plugins.NettyDemo.internal_static_DataStream_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hoang.plugins.NettyDemo.internal_static_DataStream_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hoang.plugins.NettyDemo.DataStream.class, com.hoang.plugins.NettyDemo.DataStream.Builder.class);
      }

      // Construct using com.hoang.plugins.NettyDemo.DataStream.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";

        data_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hoang.plugins.NettyDemo.internal_static_DataStream_descriptor;
      }

      @java.lang.Override
      public com.hoang.plugins.NettyDemo.DataStream getDefaultInstanceForType() {
        return com.hoang.plugins.NettyDemo.DataStream.getDefaultInstance();
      }

      @java.lang.Override
      public com.hoang.plugins.NettyDemo.DataStream build() {
        com.hoang.plugins.NettyDemo.DataStream result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.hoang.plugins.NettyDemo.DataStream buildPartial() {
        com.hoang.plugins.NettyDemo.DataStream result = new com.hoang.plugins.NettyDemo.DataStream(this);
        result.name_ = name_;
        result.data_ = data_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hoang.plugins.NettyDemo.DataStream) {
          return mergeFrom((com.hoang.plugins.NettyDemo.DataStream)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hoang.plugins.NettyDemo.DataStream other) {
        if (other == com.hoang.plugins.NettyDemo.DataStream.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getData().isEmpty()) {
          data_ = other.data_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hoang.plugins.NettyDemo.DataStream parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hoang.plugins.NettyDemo.DataStream) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object data_ = "";
      /**
       * <code>string data = 2;</code>
       * @return The data.
       */
      public java.lang.String getData() {
        java.lang.Object ref = data_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          data_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string data = 2;</code>
       * @return The bytes for data.
       */
      public com.google.protobuf.ByteString
          getDataBytes() {
        java.lang.Object ref = data_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          data_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string data = 2;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string data = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      /**
       * <code>string data = 2;</code>
       * @param value The bytes for data to set.
       * @return This builder for chaining.
       */
      public Builder setDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        data_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DataStream)
    }

    // @@protoc_insertion_point(class_scope:DataStream)
    private static final com.hoang.plugins.NettyDemo.DataStream DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.hoang.plugins.NettyDemo.DataStream();
    }

    public static com.hoang.plugins.NettyDemo.DataStream getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DataStream>
        PARSER = new com.google.protobuf.AbstractParser<DataStream>() {
      @java.lang.Override
      public DataStream parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DataStream(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DataStream> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DataStream> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.hoang.plugins.NettyDemo.DataStream getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_IndexDataStream_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_IndexDataStream_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DataStream_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DataStream_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017nettyDemo.proto\032\033google/protobuf/empty" +
      ".proto\"2\n\017IndexDataStream\022\037\n\ndataStream\030" +
      "\001 \003(\0132\013.DataStream\"(\n\nDataStream\022\014\n\004name" +
      "\030\001 \001(\t\022\014\n\004data\030\002 \001(\t2M\n\021StreamDataServic" +
      "e\0228\n\nStreamData\022\020.IndexDataStream\032\026.goog" +
      "le.protobuf.Empty(\001B\023\n\021com.hoang.plugins" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    internal_static_IndexDataStream_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_IndexDataStream_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_IndexDataStream_descriptor,
        new java.lang.String[] { "DataStream", });
    internal_static_DataStream_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_DataStream_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DataStream_descriptor,
        new java.lang.String[] { "Name", "Data", });
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
